### ISSUE TITLE
Reconnect capabilities 

### ISSUE THREAD

**Issue by yarharel** [ibm-watson-iot/iot-python#106]
WIOT client works great most of times.
On some occasions (which i can't explain), there are disconnections from WIOT platform.
Internet connections might return after these occasions , but WIOT won't try to reconnect or notify on anyway on disconnections.

Please try to add this capabilities to the python package

**Comment by jpwsutton** [comment]
Hi @yarharel,

The underlying Paho Python client already has automatic reconnect capabilities, so I would imagine that your client should have automatically reconnected. Are you using this library as an application or a device? If you let me know, I might be able to help diagnose this issue for you.

**Comment by yarharel** [comment]
As part of a Gateway/Device

So the (Manged) Gateway is connected to WIOT and through that the Devices send/receive messages/events

The Gateway doesn't receive any indication for disconnection,
Also.  messages that are being sent don't receive timeout/other error that might indicate disconnection.

In WIOT platform it shows as if the Gateway is disconnect. Reseting the client solves the issue, but do it manually since we can infer it from any other reading/parameter

**Comment by istrate** [comment]
@jpwsutton can you help on above?

**Comment by durera** [comment]
@yarharel Can you enable debug log and capture the output when this happens to aid debug of this?  After you construct your client you need to override the detault logging level

```python
client = ibmiotf.gateway.Client(options)
client.logger.setLevel(logging.DEBUG)
```

There are scenarios where the client will not auto-reconnect, and raise a `ConnectionException` back up to the user to handle so that they can make a decision about how to proceed:
- if we don't connect in 30 seconds we stop & raise an exception
- if we hit a socket error we stop & raise an exception

Are you seeing one of these exceptions raised, which one is it?

At the moment, the expectation is on the user of the library to handle the raised `ConnectionException` in their own code if either of these two scenarios occur.

In the samples we have developed using the library that is where something like supervisord or runit comes into play, the library will "swallow" most network glitches/minor disconnects, but occasionally a ConnectionException will be raised, which causes the program to exit, but the supervisor restarts it automatically.

Of course, it would be just as valid to handle ConnectionException in the python code itself in a loop, but I feel it's a cleaner approach letting the program die and having something like supervisord/runit handle lifecycle around restarts etc.
