### ISSUE TITLE
Port 443 no longer supported as fallback

### ISSUE THREAD

**Issue by mvdfugro** [ibm-watson-iot/iot-python#121]
Due to a restrictive firewall, we are unable to connect over port 8883, and we used the port 443 fallback for this. Unfortunately, this is no longer possible in 0.3.5:

Before connecting, the client checks whether the configured port is a supported port (`__init__.py:140`). The check requires the port to be either 1883 or 8883 (MQTT / MQTT-over-TLS). The comment at `__init__.py:131` suggests this is not intended, and port 80/443 should also work.

Changing `        elif self.port == 8883:` to `elif self.port in [443, 8883]` resolves the issue. I'm not 100% certain about accepting port 80, as this is not documented at fallback at [1].

[1] https://console.bluemix.net/docs/services/IoT/reference/security/connect_devices_apps_gw.html

**Comment by durera** [comment]
I originally added 80 and 443 fallback :) When I discovered 80 fallback did not work I accidentally removed 443 and fallback 80 support instead of just 80 .. 

0.3.6 will be available soon that supports port 443 fallback again and I'm going to investigate whether port 80 fallback should be working or whether it's expected that can't connect using mqtt over port 80.

**Comment by durera** [comment]
https://pypi.org/project/ibmiotf/0.3.6/ is now available with port 443 support restored
