### ISSUE TITLE
file transfer support possible?

### ISSUE THREAD

**Issue by namespace7** [ibm-watson-iot/iot-python#130]
does the library support different format ,other then json ? to update the existing file or send a file from one system to another?

**Comment by durera** [comment]
I hacve just put out a pre-release for the new `wiotp-sdk` library ahead of the finalization for 1.0  (note: there may still be a few breaking changes coming before the official 1.0 release) 

The new `RawCodec` will do what you want, it is automatically registered to handle events/commands where `format=raw`:

On the device:
```python
cwd = os.getcwd()
fileContent = None
with open("%s/README.md" % cwd, 'rb') as fileIn:
  fileContent = fileIn.read()
        
deviceCli.publishEvent("readmeContent", "raw", fileContent)
```

When the app recieves the event you will be able to get a `bytearray` containing the data from the file using `event.data` in the event callback method.

`Utf8Codec` does pretty much the same thing, but works for UTF-8 encoded strings rather than arbitrary bytes, if you're transferring UTF-8 encoded files it may be more appropriate as it would throw errors in the event any content in the file is not valid UTF-8.

Related code: 
- https://github.com/ibm-watson-iot/iot-python/blob/master/test/test_codecs_raw.py
- https://github.com/ibm-watson-iot/iot-python/blob/master/src/wiotp/sdk/messages.py

**Comment by namespace7** [comment]
Great!
