### ISSUE TITLE
Code hangs up when using on_publish callback

### ISSUE THREAD

**Issue by eifinger** [ibm-watson-iot/iot-python#78]
I have a program which checks memory consumption of a python mqtt client while sending messages with different sizes, different qos and different amount of sending times [here](https://github.com/eifinger/paho-memory-check/blob/master/paho-memory-check.py).
I am using a callback to check if all messages have successfully been published.

My code sometimes(!) hangs up when trying to send a JSON payload of size 527 bytes with qos=1.
In sometimes I mean this either happens when I try to send this combination 10 times or the when I later try to send it again 100 times.
This code works fine when I call "publishEvent" without the callback.
While debugging I found out that [this](https://github.com/eclipse/paho.mqtt.python/blob/f53da37ce6305f4be081106c46942112465f52be/src/paho/mqtt/client.py#L1091) line in the paho lib hangs.
This happens on Windows and Linux alike.

When I attach my callback function to the paho client directly like [this](https://github.com/eifinger/paho-memory-check/blob/callbackInPahoDirectly/paho-memory-check.py)
the code again runs fine.

**Comment by slaupster** [comment]
hi @eifinger thanks for submitting this issue.  I suspect that the messagesLock in the iotf client is involved in the deadlock.  Its taken in the callback to ensure that the thread doing the publish actually completes before the MID correlating the callback with the message is actually created (thus assuring that we actually call the callback passed).

It could be that we need to synchronize with a different lock to avoid this deadlock and still have the exclusion desired.  To check that we are identifying the deadlock correctly, please can you provide a full thread dump to check which locks are involved ?

**Comment by eifinger** [comment]
@slaupster  Hi. 
Thank you for the fast answer.
Here is a link to the complete dump file generated via the Windows Task Manager:
https://slack-files.com/T2K16FXH7-F6Z0NEX0R-df11df027b

**Comment by slaupster** [comment]
@eifinger thanks for that.  I had trouble extracting the stacks from that Windows dump, but I've managed to recreate it with the magic 527 number.

It is as expected, an ABBA deadlock.  Luckily it looks relatively easy to fix by not taking the lock during the publish, but take it after when the MID is known and then either record the callback -> MID in the map as before, or call the callback inline if the paho client callback has already come through.

I've tested the above approach and it appears to work.  I can see that the locking is quite clearly necessary as frequently (qos 1 mainly) the paho callback comes before iotf client has recorded the mid->callback.  This also explains why qos 1 appears to be the key to recreating it as it induces the timing condition necessary.

I'll do a bit more testing and create a patch in my branch.  I'd be grateful if you could confirm for me as well, otherwise I will merge into master.

**Comment by slaupster** [comment]
@eifinger fix is in https://github.com/ibm-watson-iot/iot-python/tree/slaupster/src/ibmiotf 

I will PR it later.

thanks

**Comment by eifinger** [comment]
@slaupster I tested the fix and my code runs through.
To explain the "magic number": "iteration 100_527_1" means "send 100 times a payload of (utf-8)byte-size 527 with qos 1" ;-)

Thank you for the fast and kind help!

**Comment by slaupster** [comment]
thanks @eifinger I've merge these changes into master and they will be in the next release of the client.
