### ISSUE TITLE
Delay in messages sent via publishGatewayEvent

### ISSUE THREAD

**Issue by nanowireUK** [ibm-watson-iot/iot-python#92]
I'm writing a Python3 script that is meant to send messages to WIoT after it completes certain steps in a method. The problem I have is that these messages are never sent in the order I generate them and instead are sent in one big batch once my overall method completes. I believe it has something to do with the way Python handles threads. I have tried a number of ways of solving this but no success.

I understand why it's been written in a non-blocking way but equally need a method to send a message now and only continue once sent (or advice on how I should write my code so it opens up to allow the messages to be sent).

**Comment by nanowireUK** [comment]
Thanks @durera. The on_publish CB won't help me unless I fundamentally rewrite how the application works (not saying that it's right the way it is). The send event method is effectively an analog to a logging function, it's just it's reasonably time sensitive since it drives the UI the user sees.

The timing issue is way more than milliseconds. I'm calling the send event maybe 5 times over the course of 10 seconds. The behavior every time is that I get all 5 events as a batch at an identical time.

Code snippet might be difficult since the whole thing is tightly bound into how the application is structured. It's a big ask but could I perhaps get 30 min of your time to show you through what we were are doing and where it's going wrong?

**Comment by nanowireUK** [comment]
Confirmed through enhanced logging that the client believes it is sending the messages at the correct time but they are still arriving at the platform in batches despite being sent 2 seconds apart.

**Comment by durera** [comment]
I'm using simpleApp and simpleDevice to try to reproduce this:

SimpleDevice (https://github.com/ibm-watson-iot/iot-python/tree/master/samples/simpleDevice) is configured to send an event every 2 seconds: `python simpleDevice.py -c device.cfg -N 100 -D 2`

The subscribing application (https://github.com/ibm-watson-iot/iot-python/tree/master/samples/simpleApp) receives all the event as expected at 2 second intervals, no batching: `python simpleApp.py -c application.cfg`

```
2018-04-03T15:42:40.518000+00:00 test:1002                     event: {"x": 0, "simpledev": "ok"}
2018-04-03T15:42:42.418000+00:00 test:1002                     event: {"x": 1, "simpledev": "ok"}
2018-04-03T15:42:44.418000+00:00 test:1002                     event: {"x": 2, "simpledev": "ok"}
2018-04-03T15:42:46.420000+00:00 test:1002                     event: {"x": 3, "simpledev": "ok"}
2018-04-03T15:42:48.420000+00:00 test:1002                     event: {"x": 4, "simpledev": "ok"}
2018-04-03T15:42:50.426000+00:00 test:1002                     event: {"x": 5, "simpledev": "ok"}
2018-04-03T15:42:52.422000+00:00 test:1002                     event: {"x": 6, "simpledev": "ok"}
2018-04-03T15:42:54.423000+00:00 test:1002                     event: {"x": 7, "simpledev": "ok"}
2018-04-03T15:42:56.423000+00:00 test:1002                     event: {"x": 8, "simpledev": "ok"}
```

How exactly are you determining/measuring "arriving at the platform"?  If you are using the last event cache, the timestamps are *the time the event makes it into the cache, not the time it's received*.  Events are received (and distributed to subscribers) in real time, and in parallel are written to the last event cache in batches.  The cache is not real-time, like an MQTT subscription.  

So, if you are using the time that the event hit's the cache to measure "recieved by the platform" rather than receipt from an connected application via a MQTT subscription then that may be where this appearance of batching is coming from.  It's the only explanation I can think of at the moment anyway :)

**Comment by nanowireUK** [comment]
Thanks David. A more accurate way of testing would be to create a function that gets called and within this it includes multiple calls to the platform with delays in between. I'm sending you an example by Slack. I can't however reproduce the issue using the simpledevice modification I made. There is something else going on in my code.

**Comment by nanowireUK** [comment]
We discovered that this was caused by us having a sleep() earlier in the code; removing this solved the issue. Seems to have done something to the thread which was only released after the function completed. If any fix required than it's in the Paho library rather than this project. Thanks for your help @durera.
